// <auto-generated />
namespace TyNi.Wedding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class removedvenuescollectionfrommenuandreplacewithsinglevenue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedvenuescollectionfrommenuandreplacewithsinglevenue));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241624097_removed venues collection from menu and replace with single venue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
