// <auto-generated />
namespace TyNi.Wedding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updatedmenuwithrequiredfieldwhichcanbeusedforvalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedmenuwithrequiredfieldwhichcanbeusedforvalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201805290852465_updated menu with required field which can be used for validation "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
